FROM cr.weaviate.io/semitechnologies/weaviate:1.29.1

ENV AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
ENV PERSISTENCE_DATA_PATH=/var/lib/weaviate
ENV QUERY_DEFAULTS_LIMIT=25
ENV ENABLE_MODULES=text2vec-mistral
ENV TEXT2VEC_MISTRAL_API_KEY=${MISTRAL_AI_TOKEN}
ENV CLUSTER:false


EXPOSE 8080

CMD ["weaviate"]
